spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: test
    url: jdbc:mysql://172.16.10.44:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true

